# Generated by Django 4.1 on 2022-08-24 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidDebts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrual', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.accrual')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.payment')),
            ],
        ),
    ]
