# Generated by Django 4.1 on 2022-08-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_paiddebts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaidDebts',
            new_name='PaidDebt',
        ),
    ]
