# Generated by Django 4.1 on 2022-08-24 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_rename_paiddebts_paiddebt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiddebt',
            name='accrual',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Finance.accrual'),
        ),
        migrations.AlterField(
            model_name='paiddebt',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Finance.payment'),
        ),
    ]
