# Generated by Django 4.1 on 2022-08-25 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0004_alter_paiddebt_accrual_alter_paiddebt_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrual',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
